//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grafer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grafer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English;Czech;
        ///Minimum can&apos;t be higher than maximum.;Minimum nemůže být větší jak maximum.;
        ///Minimum and maximum x can&apos;t be same.;Minimum nemůže býýt stejné jako maximum.;
        ///Function won&apos;t be plotted because x&apos;s range is outside of drawing canvas.;Funkce nebude vykreslena, protože rozsah x je mimo vyditelnou plochu.;
        ///cannot be empty.;nemůže být prázdné.;
        ///begins with invalid character.;začíná nevalidním znakem.;
        ///ends with invalid character.;končí nevalidním znakem.;
        ///cannot contain more than one minus or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut;Output;
        ///ShiftN;^;
        ///ShiftD;√;
        ///ShiftS;sin;
        ///ShiftC;cos;
        ///ShiftT;tg;
        ///ShiftG;cotg;
        ///ShiftO;°;
        ///ShiftP;π;
        ///ShiftL;log[10];
        ///ControlS;sin⁻¹;
        ///ControlC;cos⁻¹;
        ///ControlT;tg⁻¹;
        ///ControlG;cotg⁻¹;
        ///ControlL;ln;.
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component name;English;Czech;
        ///labelLanguage;Language:;Jazyk:;
        ///buttonsShowHelp;Help;Nápověda;
        ///labelCoordinateSystem;Coordinate system;Soustava souřadnic;
        ///checkBoxShowGrid;Show grid;Mřížka;
        ///checkBoxShowGridLabels;Show grid&apos;s labels;Popisky mřížky;
        ///checkBoxShowPointer;Show pointer;Ukazovátko;
        ///buttonShowHideMarkSettings;Mark axis;Posunutí os;
        ///buttonExportCoordinateSystem;Take a snap;Vyfotit;
        ///labelMultipleFunctionsControl;List of functions;Seznam funkcí;
        ///buttonLoadFunctions;Load Functions;Načíst funkce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UILocalization {
            get {
                return ResourceManager.GetString("UILocalization", resourceCulture);
            }
        }
    }
}
